export const METRIC = {
  ERROR_COUNT: 'error.count',
  WEB_MEMORY_USAGE: 'web.memory.usage',
  WEB_CPU_USAGE: 'web.cpu.usage',
  WEB_FRAME_TIME: 'web.frame.time',
  WEB_VITAL_LCP: 'web.vital.lcp',
  WEB_VITAL_FID: 'web.vital.fid',
  WEB_VITAL_CLS: 'web.vital.cls',
  WEB_VITAL_INP: 'web.vital.inp',
  WEB_VITAL_TTFB: 'web.vital.ttfb',
  WEB_VITAL_FCP: 'web.vital.fcp',
  RN_MEMORY_USAGE: 'react_native.memory.usage',
  RN_CPU_USAGE: 'react_native.cpu.usage',
  RN_FRAME_BUILD_TIME: 'react_native.frame.build_time',
  RN_FRAME_DROPPED: 'react_native.frame.dropped',
  RN_FRAME_REFRESH_RATE: 'react_native.frame.refresh_rate',
  RN_FRAME_SLOW_FRAMES_RATE: 'react_native.frame.slow_frames_rate',
  RN_FRAME_FREEZE_RATE: 'react_native.frame.freeze_rate',
  RN_FRAME_JS_REFRESH_RATE: 'react_native.frame.js_refresh_rate',
  VIEW_ACTION_COUNT: 'view.action.count',
  VIEW_ERROR_COUNT: 'view.error.count',
  VIEW_CRASH_COUNT: 'view.crash.count',
  VIEW_LONG_TASK_COUNT: 'view.long_task.count',
  VIEW_FROZEN_FRAME_COUNT: 'view.frozen_frame.count',
  VIEW_RESOURCE_COUNT: 'view.resource.count',
  VIEW_FRUSTRATION_COUNT: 'view.frustration.count',
} as const;
