export const SPAN = {
    USER_INTERACTION: 'user_interaction',
    SCREEN_VIEW: 'screen_view',
    SCREEN_LOAD: 'screen_load',
    VIEW_SESSION: 'view_session',
    APP_STARTUP: 'app_startup',
    APP_PAUSED: 'app_paused',
    APP_RESUMED: 'app_resumed',
    APP_CRASH: 'app_crash',
    NATIVE_CRASH: 'native_crash',
    ERROR: 'error',
    LONG_TASK: 'long_task',
    FROZEN_FRAME: 'frozen_frame',
    ANR: 'anr',
    HTTP_REQUEST: 'http.request',
    WEB_VITAL: 'web_vital',
    CUSTOM_TIMING: 'custom_timing',
    CUSTOM_VITAL: 'custom_vital',
    OPERATION_STEP: 'operation_step',
} as const;
export const BREADCRUMB_TYPE = {
    TAP: 'tap',
    NAVIGATION: 'navigation',
    VIEW_SESSION: 'view_session',
    LIFECYCLE: 'lifecycle',
    STARTUP: 'startup',
    ERROR: 'error',
    LONG_TASK: 'long_task',
    ANR: 'anr',
    FROZEN_FRAME: 'frozen_frame',
    HTTP: 'http',
} as const;
